
- name: Update apt-get and install required packages
  apt:
    update_cache: yes
    name:
      - unzip
      - curl
      - npm
    state: present
  become: yes

- name: Create tmp directory
  file:
    path: /tmp/awscli_install
    state: directory

- name: Download AWS CLI v2
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture }}.zip"
    dest: /tmp/awscli_install/awscliv2.zip

- name: Unzip AWS CLI v2
  unarchive:
    src: /tmp/awscli_install/awscliv2.zip
    dest: /tmp/awscli_install/
    remote_src: yes

- name: Install AWS CLI v2
  command: /tmp/awscli_install/aws/install --update
  become: yes
  
- name: Clean up tmp directory
  file:
    path: /tmp/awscli_install
    state: absent

- name: Verify AWS CLI installation
  command: aws --version
  register: aws_version_output

- name: Show AWS CLI version
  debug:
    msg: "AWS CLI version: {{ aws_version_output.stdout }}"
